name: kuryemapp
description: A new Flutter project.
publish_to: 'none' # Usually 'none' for apps not intended for pub.dev
version: 1.0.0+1

environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    # HTTP istekleri için (API çağrıları)
    http: ^1.2.1

    # Kullanıcı arayüzü ve yerelleştirme
    cupertino_icons: ^1.0.6
    intl: ^0.18.1 # Tarih/saat formatlama vb. için

    # Harita özellikleri
    flutter_map: ^6.1.0
    latlong2: ^0.9.0
    # flutter_map_marker_popup: ^8.0.1
    # flutter_map_tile_caching: ^8.0.0

    # Konum servisleri
    geolocator: ^11.0.0
    permission_handler: ^11.3.0

    # Cihaz içi depolama
    shared_preferences: ^2.2.2 # Basit anahtar-değer depolama
    sqflite: ^2.3.3          # Yerel SQLite veritabanı
    path_provider: ^2.1.3    # Dosya sistemi yollarına erişim
    path: ^1.9.0             # Dosya ve dizin yollarını işlemek için

    # Kamera ve galeri erişimi
    image_picker: ^1.1.0

    # Reaktif programlama (isteğe bağlı, debounce için kullanılıyor)
    rxdart: ^0.27.7
    stream_transform: ^2.1.0 # Alternatif olarak RxDart yerine veya RxDart ile birlikte kullanılabilir

    # Obje veritabanı (kullanılmıyorsa yorumda kalabilir)
    # objectbox_flutter_libs: any

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    flutter_launcher_icons: ^0.13.1

# Flutter Launcher Icons yapılandırması
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/logo.png"
    min_sdk_android: 21 # veya projenizin minimum SDK'sı
    # adaptive_icon_background: "#FFFFFF" # Uyarlanabilir ikon arka planı
    # adaptive_icon_foreground: "assets/images/logo_foreground.png" # Uyarlanabilir ikon ön planı

flutter:
    uses-material-design: true

    assets:
        # Genel resimler ve logolar:
        - assets/images/logo.png
        - assets/images/vigo-logo.png
        - assets/images/fiyuu-logo.png
        - assets/images/yemeksepeti-logo.png
        - assets/images/gunluk.png
        - assets/images/motorcu.png # Bu genel bir motorcu ikonu mu, yoksa avatar mı?
        - assets/images/para_say.gif

